catenax-ng/product-item-relationship-service

api/irs-v1.0.yaml, irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASRecursiveJobHandler.java, irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcess.java, irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManager.java, irs-api/src/main/java/net/catenax/irs/aaswrapper/job/ItemDataRequest.java, irs-api/src/main/java/net/catenax/irs/controllers/IrsController.java, irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java, irs-api/src/test/java/net/catenax/irs/IrsApplicationTests.java, irs-api/src/test/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManagerTest.java, irs-api/src/test/java/net/catenax/irs/connector/job/PersistentJobStoreTest.java, irs-api/src/test/java/net/catenax/irs/controllers/IrsControllerTest.java, irs-api/src/test/java/net/catenax/irs/services/IrsItemGraphQueryServiceTest.java, irs-api/src/test/java/net/catenax/irs/util/TestMother.java, irs-models/src/main/java/net/catenax/irs/component/RegisterJob.java
I need feedback if there is a need to also serialize depth in AASTransferProcessDeserializer?
=> feat(api):[TRI-339] introduce depth in recursive processing

.github/workflows/CI-main.yml
This way, it is automatically picked up by ArgoCD
=> feat(docker):[-] Tag docker image with Git commit hash as well

irs-api/pom.xml
- remove spring-boot-starter-data-jpa as its redundant
- HIBERNATE-COMMONS-ANNOTATIONS removed with above change
=> feat(dep):[TRI-378] remove spring-data-jpa as its redundant

irs-api/src/main/java/net/catenax/irs/IrsApplication.java, irs-api/src/main/java/net/catenax/irs/connector/job/JobOrchestrator.java, irs-api/src/main/resources/application-local.yml, irs-api/src/main/resources/application.yml
Added a scheduler to call the already implemented cleanup methods.
MinIO object TTL was already implemented before.
=> feat(ttl):[TRI-311] Implement scheduler for cleanup methods

irs-api/src/test/java/net/catenax/irs/controllers/IrsControllerTest.java, irs-api/src/test/java/net/catenax/irs/util/TestMother.java
https://jira.catena-x.net/browse/TRI-374
=> test(irs-api):[TRI-374] Add input validation tests for IrsController

irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManager.java, irs-api/src/main/java/net/catenax/irs/aaswrapper/registry/domain/DigitalTwinRegistryFacade.java, irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java, irs-api/src/main/java/net/catenax/irs/services/IIrsItemGraphQueryService.java, irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java, irs-api/src/test/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacadeTest.java, irs-api/src/test/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelRetryerTest.java, irs-models/src/main/java/net/catenax/irs/component/enums/BomLifecycle.java
- moved and refactored filtering - moved to SubmodelFacade. I think its the right place to do this, as AASTransferProcessManager had much more responsibility then it should have.
- added unit test
=> feat(test):[TRI-434] refactor filtering, implementing unit test

irs-api/src/main/java/net/catenax/irs/aaswrapper/submodel/domain/SubmodelFacade.java, irs-api/src/test/java/net/catenax/irs/aaswrapper/submodel/domain/AASWrapperUriAddressRewritePolicyTest.java
fixing npe of bad data quality
=> feat(fix):[TRI-507] fix encoding

irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java, irs-api/src/main/resources/application-local.yml
Set BomLifecycle.AS_BUILT as default value
=> feat(impl):[TRI-518] - set asBuild as default lifecycle

api/irs-v1.0.yaml, irs-api/src/main/java/net/catenax/irs/configuration/OpenApiExamples.java, irs-api/src/main/java/net/catenax/irs/connector/job/JobOrchestrator.java, irs-models/src/main/java/net/catenax/irs/component/JobParameter.java
Added missing job parameter "collectAspects" to job response
=> TRI-509-Enable-IRS-to-collect-Submodel-information

chart/grafana/templates/configmap.yaml, chart/grafana/templates/deployment.yaml, chart/grafana/values.yaml
adding default prometheus datasource
=> feat(impl):[TRI-313] adding default datasource

irs-api/src/main/java/net/catenax/irs/configuration/MinioHealthIndicator.java, irs-api/src/main/java/net/catenax/irs/persistence/MinioBlobPersistence.java, irs-api/src/test/java/net/catenax/irs/configuration/MinioHealthIndicatorTest.java, irs-api/src/test/java/net/catenax/irs/util/CommonConstant.java
Minio health indicator for Spring actuator added
=> feat(impl):[TRI-570] minio health actuator

testing/IRS_PEN.postman_environment.json
=> feat(impl):[TRI-567] pen env for postman

testing/IRS DEMO Collection.postman_collection.json
Update postman collection with working globalAssetId
=> feat(test):[TRI-568] update postman with working globalAssetId

api/irs-v1.0.yaml, irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASHandler.java, irs-api/src/main/java/net/catenax/irs/configuration/JobConfiguration.java, irs-api/src/main/java/net/catenax/irs/configuration/OpenApiExamples.java, irs-api/src/test/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManagerTest.java, irs-models/src/main/java/net/catenax/irs/component/Submodel.java
Changes String raw payload to HashMap
=> feat(impl):[TRI-634] change String raw payload to HashMap

irs-api/src/main/resources/application.yml
=> feat(comment):[TRI-636] add cron comment

api/irs-v1.0.yaml, integration-tests/src/test/java/net/catenax/irs/smoketest/ItemGraphSmokeTest.java, irs-api/src/main/java/net/catenax/irs/aaswrapper/job/AASHandler.java, irs-api/src/main/java/net/catenax/irs/aaswrapper/job/ItemContainer.java, irs-api/src/main/java/net/catenax/irs/aaswrapper/job/ItemTreesAssembler.java, irs-api/src/main/java/net/catenax/irs/aaswrapper/registry/domain/AssetAdministrationShellTestdataCreator.java, irs-api/src/main/java/net/catenax/irs/bpdm/BpdmClient.java, irs-api/src/main/java/net/catenax/irs/bpdm/BpdmFacade.java, irs-api/src/main/java/net/catenax/irs/bpdm/BusinessPartnerResponse.java, irs-api/src/main/java/net/catenax/irs/bpdm/NameResponse.java, irs-api/src/main/java/net/catenax/irs/configuration/JobConfiguration.java, irs-api/src/main/java/net/catenax/irs/configuration/OpenApiExamples.java, irs-api/src/main/java/net/catenax/irs/services/IrsItemGraphQueryService.java, irs-api/src/main/resources/application.yml, irs-api/src/test/java/net/catenax/irs/IrsFunctionalTest.java, irs-api/src/test/java/net/catenax/irs/aaswrapper/job/AASTransferProcessManagerTest.java, irs-api/src/test/java/net/catenax/irs/bpdm/BpdmClientImplTest.java, irs-api/src/test/java/net/catenax/irs/bpdm/BpdmFacadeTest.java, irs-models/src/main/java/net/catenax/irs/component/Bpn.java, irs-models/src/main/java/net/catenax/irs/component/Jobs.java, irs-models/src/main/java/net/catenax/irs/component/assetadministrationshell/AssetAdministrationShellDescriptor.java
- added bpn mapping to job response
=> feat(impl):[TRI-633] bpn mapping call

.run/IrsApplication.run.xml, api/irs-v1.0.yaml, irs-api/src/main/java/net/catenax/irs/configuration/OpenApiExamples.java, irs-api/src/main/java/net/catenax/irs/controllers/IrsController.java
Fixed api documentation for 400 and 404 status codes
=> feat(impl):[TRI-655] fix api docs for errors

.github/workflows/kics.yml
- Exclude api contract
- Its easier for me to create few smaller pull requests for kics fixes...
=> feat(impl):[TRI-643] - exclude api yaml contract

api/irs-v1.0.yaml, irs-models/src/main/java/net/catenax/irs/component/enums/AspectType.java
Enabling collecting Batches submodels. Johannes needs it for creating test case.
=> feat(impl):[TRI-558] - enabling collecting Batches submodels

docker-compose.yml
- Most of docker-compose findinding should be fixed
- Its easier for me to create few smaller pull requests for kics fixes...
=> feat(impl):[TRI-643] - some fixes for docker-compose

chart/aasregistry/templates/deployment.yaml, chart/aasregistry/templates/hpa.yaml, chart/aasregistry/templates/ingress.yaml, chart/aasregistry/templates/service.yaml, chart/aasregistry/values.yaml
- Part of fixes for aasregistry helm chart
- Its easier for me to create few smaller pull requests for kics fixes...
=> feat(impl):[TRI-643] - some fixes for aasregistry helm chart

.github/workflows/kics.yml
=> feat(fix):[TRI-643] exclude api yaml

.github/workflows/CI-branches.yml, .github/workflows/CI-main.yml, .github/workflows/eclipse-dash.yml, DEPENDENCIES, pom.xml
https://jira.catena-x.net/browse/TRI-605
=> feat(cicd):[TRI-605] Add dash tool execution and result upload to CI workflows

.github/workflows/kics.yml
Added the false positives to the KICS exclusion list so the job is green again.
=> fix(kics):[TRI-643] Store KICS json result file

irs-api/src/main/resources/application.yml, testing/IRS DEMO Collection.postman_collection.json
Temporary switch to v1 as its working (v2 needs some migration)
=> feat(fix):[TRI-XXX] switch to v1 temporary

Dockerfile, esr/pom.xml, irs-api/pom.xml, pom.xml
=> feat(impl):[TRI-677] new module for esr microservice

testdata-transform/transform-and-upload.py
Added criteria to EDC contract definition to reduce size of catalog
=> chore(testdata):[-] Add criteria to contract definition

CONTRIBUTING.md, README.md
Update README.md
move semantic message hook to CONTRIBUTING.md
=> (chore) Update README

esr/src/main/java/org/eclipse/tractusx/esr/irs/IrsClient.java, esr/src/main/java/org/eclipse/tractusx/esr/irs/IrsFacade.java, esr/src/main/java/org/eclipse/tractusx/esr/service/EsrService.java, esr/src/test/java/org/eclipse/tractusx/esr/irs/IrsClientTest.java, esr/src/test/java/org/eclipse/tractusx/esr/irs/IrsFacadeTest.java, esr/src/test/java/org/eclipse/tractusx/esr/service/EsrServiceTest.java, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/SecurityConfiguration.java
- public access to ESR endpoint
- added rest template with interceptor to keycloak auth for IRS client
=> feat(impl):[TRI-630] public access to ESR endpoint

esr/src/main/java/org/eclipse/tractusx/esr/controller/model/EsrCertificateStatistics.java, esr/src/main/java/org/eclipse/tractusx/esr/irs/model/shell/SubmodelDescriptor.java, esr/src/main/java/org/eclipse/tractusx/esr/service/EsrCertificateAggregation.java, esr/src/main/java/org/eclipse/tractusx/esr/service/EsrService.java, esr/src/test/java/org/eclipse/tractusx/esr/controller/model/EsrCertificateStatisticsTest.java, esr/src/test/java/org/eclipse/tractusx/esr/irs/IrsFacadeTest.java, esr/src/test/java/org/eclipse/tractusx/esr/irs/IrsFixture.java, esr/src/test/java/org/eclipse/tractusx/esr/irs/model/shell/SubmodelDescriptorTest.java, esr/src/test/java/org/eclipse/tractusx/esr/service/EsrCertificateAggregationTest.java, esr/src/test/java/org/eclipse/tractusx/esr/service/EsrServiceTest.java
- searching for ESR statics submodel descriptor
- call endpoint for stastics
- aggegate result to one object
=> TRI-694 implementation of recurence mechanism to aggregate ESR stats

esr/src/main/java/org/eclipse/tractusx/esr/irs/IrsResponse.java, esr/src/main/java/org/eclipse/tractusx/esr/irs/model/shell/Shell.java, esr/src/test/java/org/eclipse/tractusx/esr/irs/model/shell/ShellTest.java
- added validation of regexp during BPN retrieval
=> feat(impl):[TRI-640] added validation of regexp during BPN retrieval

charts/irs/templates/deployment.yaml, charts/irs/templates/secrets.yaml, charts/irs/values-dev.yaml, charts/irs/values-esr.yaml, charts/irs/values-int.yaml, charts/irs/values-pen.yaml, esr/src/main/java/org/eclipse/tractusx/esr/irs/IrsClient.java, esr/src/main/java/org/eclipse/tractusx/esr/service/EsrService.java, esr/src/main/java/org/eclipse/tractusx/esr/supplyon/SupplyOnClient.java, esr/src/main/java/org/eclipse/tractusx/esr/supplyon/SupplyOnFacade.java, esr/src/test/java/org/eclipse/tractusx/esr/irs/IrsClientTest.java, esr/src/test/java/org/eclipse/tractusx/esr/service/EsrServiceTest.java, esr/src/test/java/org/eclipse/tractusx/esr/supplyon/SupplyOnClientTest.java, irs-api/src/main/resources/application.yml
Rest client to SpplyOn service implementation
=> feat(impl):[TRI-630] rest client to supply on implementation

irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/DigitalTwinDelegateTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/RelationshipDelegateTest.java
DigitalTwin and Relationship Delegate
=> TRI-754 Add unit tests for creation of tombstone in delegates

.github/workflows/codeql.yml, .github/workflows/eclipse-dash-ip-create.yml, .github/workflows/eclipse-dash.yml, .github/workflows/owasp.yml, .github/workflows/veracode.yaml
Improved GitHub action execution time by adding skipTests and batch mode where possible 
Switch CodeQL action to maven build and added maven package caching.
=> Chore/improve GitHub actions

CHANGELOG.md, api/irs-v1.0.yaml, irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/BpdmDelegate.java, irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/DigitalTwinDelegate.java, irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/RelationshipDelegate.java, irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/SubmodelDelegate.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/BpdmDelegateTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/DigitalTwinDelegateTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/RelationshipDelegateTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/SubmodelDelegateTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/component/tombstone/TombStoneTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/util/TestMother.java, irs-models/src/main/java/org/eclipse/tractusx/irs/component/Tombstone.java, irs-models/src/main/java/org/eclipse/tractusx/irs/component/enums/ProcessStep.java
https://jira.catena-x.net/browse/TRI-638
=> feat(irs-api):[TRI-638] Add processStep to ProcessingError

docs/pom.xml, docs/src/docs/administration/configuration.adoc
I added some description for the configuration values. Please have a look at that and check whether the description is correct and sufficient.
Perspective: someone working in the Catena-X organization wants to deploy the IRS without any knowledge about it. :)
=> feat(docs):[TRI-593] Add description of config values

irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/TreeRecursiveLogic.java, irs-api/src/main/java/org/eclipse/tractusx/irs/connector/job/JobOrchestrator.java
There was a small bug, that callbackUrl was pigned with state RUNNING - meaning that job didnt really finished yet.
Additionaly I removed logging big json to console.
=> feat(fix):[TRI-742] - fix sending event when job not finished

api/irs-v1.0.yaml, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/OpenApiExamples.java, irs-api/src/test/java/org/eclipse/tractusx/irs/connector/job/MultiTransferJobTest.java, irs-models/src/main/java/org/eclipse/tractusx/irs/component/enums/AspectType.java
Reverts catenax-ng/product-item-relationship-service#416
=> Revert "fix(api):[TRI-796] update aspects to released 2.0.0 aspects"

testing/IRS DEMO Collection.postman_collection.json
=> feat(test):[TRI-806] add postman collection calls

api/irs-v1.0.yaml, irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/submodel/domain/RelationshipAspect.java, irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/submodel/domain/SingleLevelUsageAsBuilt.java, irs-api/src/main/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryService.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/submodel/domain/RelationshipAspectTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/submodel/domain/SubmodelFacadeTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryServiceSpringBootTest.java, irs-models/src/main/java/org/eclipse/tractusx/irs/component/enums/AspectType.java, irs-models/src/main/java/org/eclipse/tractusx/irs/component/enums/BomLifecycle.java, irs-models/src/main/java/org/eclipse/tractusx/irs/component/enums/Direction.java
- IRS supports upward traversal using SingleLevelUsageAsBuilt aspect now
- testdata is missing :)
- upward&asPlanned returnig Bad Request for now
=> feat(impl):[TRI-741] business logic impl for new aspect submodel

api/irs-v1.0.yaml, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/OpenApiExamples.java, irs-api/src/main/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryService.java, irs-api/src/test/java/org/eclipse/tractusx/irs/controllers/IrsControllerTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryServiceTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/util/TestMother.java, irs-models/src/main/java/org/eclipse/tractusx/irs/component/JobStatusResult.java
=> feat(impl):[TRI-839] - extended job state response

CHANGELOG.md, api/irs-v1.0.yaml, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/OpenApiExamples.java, irs-api/src/main/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryService.java, irs-api/src/test/java/org/eclipse/tractusx/irs/controllers/IrsControllerTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryServiceTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/util/TestMother.java, irs-models/src/main/java/org/eclipse/tractusx/irs/component/JobStatusResult.java
- add changelog entries
- use correct field name
=> feat(impl):[TRI-839] add changelog entries, use correct field name
